### PR TITLE
New instance registry

### PR DESCRIPTION
**Pull request by Ayybeeshafi**
Implementation of new functions with respect to new API. Registering and deregistering from within the docker container #23

### CODE REVIEW

**Comment by Ayybeeshafi** [comment]
reviewed by @johannesduesing

**Comment by bhermann** [comment]
After merging this, I saw today that there was a rogue submodule in here. In my review I overlooked that, but please make sure, you do not introduce unnecessary submodules in here.

**Comment by bhermann** [comment]
After merging this, I saw today that there was a rogue submodule in here. In my review I overlooked that, but please make sure, you do not introduce unnecessary submodules in here.

**Comment by bhermann** [comment]
After merging this, I saw today that there was a rogue submodule in here. In my review I overlooked that, but please make sure, you do not introduce unnecessary submodules in here.

**Pull request merged**
