### PR TITLE
Feature/instanceregistry

### PR DESCRIPTION
**Pull request by 24santoshr**
Changes for Instance registry. Please let me know for any changes

### CODE REVIEW

**Comment by bhermann** [comment]
This PR still has some open review comments.

**Comment by 24santoshr** [comment]
Hello Ben, please review the request and let me know if any changes are required.

**Comment by bhermann** [comment]
@johannesduesing We also need your approval here. Please have a look.

**Comment by johannesduesing** [comment]
I'm happy with the changes, the PR looks good to me. Snyk reports 2 vulerabilities to DoS attacks trough spray-json, do you know if we can do something about that @bhermann ?

**Pull request merged**
